#!/bin/bash
#PBS -N jupyterTest
#PBS -m abe
###PBS -M s2952109@griffithuni.edu.au
#PBS -q small_long
#PBS -l select=1:ncpus=1:mem=8gb,walltime=5:00:00

# get tunneling info
XDG_RUNTIME_DIR=""
node=$(hostname -s)
user=$(whoami)
cluster="gc-prd-hpclogin1"
port=8889
##choose your own unique port between 8000 and 9999

cd $PBS_O_WORKDIR
# print tunneling instructions to tunnel.$PBS_JOBID.txt
JJID=`echo $PBS_JOBID|sed 's/\.gc-prd-hpcadm//g'`
echo -e "
Command to create ssh tunnel:
ssh -N -f -L ${port}:${node}:${port} ${user}@${cluster}.rcs.griffith.edu.au

Use a Browser on your local machine to go to:
localhost:${port}  (prefix w/ https:// if using password)" >tunnel.$JJID.txt
# load modules or conda environments here
module load anaconda3/2021.11
source activate s2952109-cpu
# Run Jupyter
jupyter-notebook --no-browser --port=${port} --ip=${node} 2>&1 | tee jupnote.$JJID.log